name: Build and Push
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: npm i

      - name: Run Build
        env:
          GITHUB_CI_BUILD: "YES"
          SECRET_UPLOAD_URL: "${{ secrets.UPLOAD_URL }}"
          SECRET_KEY: "${{ secrets.KEY }}"
        run: npm run build